// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: access_token_payload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessTokenPayload_Role int32

const (
	AccessTokenPayload_UNKNOWN AccessTokenPayload_Role = 0
	AccessTokenPayload_GAMER   AccessTokenPayload_Role = 1
	AccessTokenPayload_ADMIN   AccessTokenPayload_Role = 2
)

// Enum value maps for AccessTokenPayload_Role.
var (
	AccessTokenPayload_Role_name = map[int32]string{
		0: "UNKNOWN",
		1: "GAMER",
		2: "ADMIN",
	}
	AccessTokenPayload_Role_value = map[string]int32{
		"UNKNOWN": 0,
		"GAMER":   1,
		"ADMIN":   2,
	}
)

func (x AccessTokenPayload_Role) Enum() *AccessTokenPayload_Role {
	p := new(AccessTokenPayload_Role)
	*p = x
	return p
}

func (x AccessTokenPayload_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessTokenPayload_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_access_token_payload_proto_enumTypes[0].Descriptor()
}

func (AccessTokenPayload_Role) Type() protoreflect.EnumType {
	return &file_access_token_payload_proto_enumTypes[0]
}

func (x AccessTokenPayload_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessTokenPayload_Role.Descriptor instead.
func (AccessTokenPayload_Role) EnumDescriptor() ([]byte, []int) {
	return file_access_token_payload_proto_rawDescGZIP(), []int{0, 0}
}

type AccessTokenPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletAddress string                  `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	Role          AccessTokenPayload_Role `protobuf:"varint,3,opt,name=role,proto3,enum=pb.AccessTokenPayload_Role" json:"role,omitempty"`
	IssuedAt      *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *AccessTokenPayload) Reset() {
	*x = AccessTokenPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_access_token_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessTokenPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessTokenPayload) ProtoMessage() {}

func (x *AccessTokenPayload) ProtoReflect() protoreflect.Message {
	mi := &file_access_token_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessTokenPayload.ProtoReflect.Descriptor instead.
func (*AccessTokenPayload) Descriptor() ([]byte, []int) {
	return file_access_token_payload_proto_rawDescGZIP(), []int{0}
}

func (x *AccessTokenPayload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessTokenPayload) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *AccessTokenPayload) GetRole() AccessTokenPayload_Role {
	if x != nil {
		return x.Role
	}
	return AccessTokenPayload_UNKNOWN
}

func (x *AccessTokenPayload) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *AccessTokenPayload) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_access_token_payload_proto protoreflect.FileDescriptor

var file_access_token_payload_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x9b, 0x02, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x77, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x2f, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x12, 0x37, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x41, 0x74, 0x22, 0x29, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x41, 0x4d,
	0x45, 0x52, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x02, 0x42,
	0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x79,
	0x61, 0x6d, 0x61, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_access_token_payload_proto_rawDescOnce sync.Once
	file_access_token_payload_proto_rawDescData = file_access_token_payload_proto_rawDesc
)

func file_access_token_payload_proto_rawDescGZIP() []byte {
	file_access_token_payload_proto_rawDescOnce.Do(func() {
		file_access_token_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_access_token_payload_proto_rawDescData)
	})
	return file_access_token_payload_proto_rawDescData
}

var file_access_token_payload_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_access_token_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_access_token_payload_proto_goTypes = []interface{}{
	(AccessTokenPayload_Role)(0),  // 0: pb.AccessTokenPayload.Role
	(*AccessTokenPayload)(nil),    // 1: pb.AccessTokenPayload
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_access_token_payload_proto_depIdxs = []int32{
	0, // 0: pb.AccessTokenPayload.role:type_name -> pb.AccessTokenPayload.Role
	2, // 1: pb.AccessTokenPayload.issued_at:type_name -> google.protobuf.Timestamp
	2, // 2: pb.AccessTokenPayload.expires_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_access_token_payload_proto_init() }
func file_access_token_payload_proto_init() {
	if File_access_token_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_access_token_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessTokenPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_access_token_payload_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_access_token_payload_proto_goTypes,
		DependencyIndexes: file_access_token_payload_proto_depIdxs,
		EnumInfos:         file_access_token_payload_proto_enumTypes,
		MessageInfos:      file_access_token_payload_proto_msgTypes,
	}.Build()
	File_access_token_payload_proto = out.File
	file_access_token_payload_proto_rawDesc = nil
	file_access_token_payload_proto_goTypes = nil
	file_access_token_payload_proto_depIdxs = nil
}
